// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: ContextProto.proto

package br.com.proto;

public final class ContextProto {

	private ContextProto() {}

	public static void registerAllExtensions( com.google.protobuf.ExtensionRegistryLite registry ) {}

	public static void registerAllExtensions( com.google.protobuf.ExtensionRegistry registry ) {
		registerAllExtensions( (com.google.protobuf.ExtensionRegistryLite) registry );
	}

	public interface ContextRequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:br.com.proto.ContextRequest)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string key = 1;</code>
		 */
		java.lang.String getKey();

		/**
		 * <code>string key = 1;</code>
		 */
		com.google.protobuf.ByteString getKeyBytes();

		/**
		 * <code>string value = 2;</code>
		 */
		java.lang.String getValue();

		/**
		 * <code>string value = 2;</code>
		 */
		com.google.protobuf.ByteString getValueBytes();
	}

	/**
	 * Protobuf type {@code br.com.proto.ContextRequest}
	 */
	public static final class ContextRequest extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:br.com.proto.ContextRequest)
		ContextRequestOrBuilder {

		private static final long serialVersionUID = 0L;

		// Use ContextRequest.newBuilder() to construct.
		private ContextRequest( com.google.protobuf.GeneratedMessageV3.Builder< ? > builder ) {
			super( builder );
		}

		private ContextRequest() {
			key_ = "";
			value_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private ContextRequest(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
				.newBuilder();
			try {
				boolean done = false;
				while ( !done ) {
					int tag = input.readTag();
					switch ( tag ) {
						case 0:
							done = true;
							break;
						default: {
							if ( !parseUnknownFieldProto3( input, unknownFields, extensionRegistry, tag ) ) {
								done = true;
							}
							break;
						}
						case 10: {
							java.lang.String s = input.readStringRequireUtf8();

							key_ = s;
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();

							value_ = s;
							break;
						}
					}
				}
			} catch ( com.google.protobuf.InvalidProtocolBufferException e ) {
				throw e.setUnfinishedMessage( this );
			} catch ( java.io.IOException e ) {
				throw new com.google.protobuf.InvalidProtocolBufferException( e ).setUnfinishedMessage( this );
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.com.proto.ContextProto.internal_static_br_com_proto_ContextRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.com.proto.ContextProto.internal_static_br_com_proto_ContextRequest_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					br.com.proto.ContextProto.ContextRequest.class,
					br.com.proto.ContextProto.ContextRequest.Builder.class );
		}

		public static final int KEY_FIELD_NUMBER = 1;

		private volatile java.lang.Object key_;

		/**
		 * <code>string key = 1;</code>
		 */
		public java.lang.String getKey() {
			java.lang.Object ref = key_;
			if ( ref instanceof java.lang.String ) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				key_ = s;
				return s;
			}
		}

		/**
		 * <code>string key = 1;</code>
		 */
		public com.google.protobuf.ByteString getKeyBytes() {
			java.lang.Object ref = key_;
			if ( ref instanceof java.lang.String ) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
					.copyFromUtf8( (java.lang.String) ref );
				key_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int VALUE_FIELD_NUMBER = 2;

		private volatile java.lang.Object value_;

		/**
		 * <code>string value = 2;</code>
		 */
		public java.lang.String getValue() {
			java.lang.Object ref = value_;
			if ( ref instanceof java.lang.String ) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				value_ = s;
				return s;
			}
		}

		/**
		 * <code>string value = 2;</code>
		 */
		public com.google.protobuf.ByteString getValueBytes() {
			java.lang.Object ref = value_;
			if ( ref instanceof java.lang.String ) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
					.copyFromUtf8( (java.lang.String) ref );
				value_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if ( isInitialized == 1 )
				return true;
			if ( isInitialized == 0 )
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo( com.google.protobuf.CodedOutputStream output ) throws java.io.IOException {
			if ( !getKeyBytes().isEmpty() ) {
				com.google.protobuf.GeneratedMessageV3.writeString( output, 1, key_ );
			}
			if ( !getValueBytes().isEmpty() ) {
				com.google.protobuf.GeneratedMessageV3.writeString( output, 2, value_ );
			}
			unknownFields.writeTo( output );
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if ( size != -1 )
				return size;

			size = 0;
			if ( !getKeyBytes().isEmpty() ) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize( 1, key_ );
			}
			if ( !getValueBytes().isEmpty() ) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize( 2, value_ );
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals( final java.lang.Object obj ) {
			if ( obj == this ) {
				return true;
			}
			if ( !( obj instanceof br.com.proto.ContextProto.ContextRequest ) ) {
				return super.equals( obj );
			}
			br.com.proto.ContextProto.ContextRequest other = (br.com.proto.ContextProto.ContextRequest) obj;

			boolean result = true;
			result = result && getKey().equals( other.getKey() );
			result = result && getValue().equals( other.getValue() );
			result = result && unknownFields.equals( other.unknownFields );
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if ( memoizedHashCode != 0 ) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = ( 19 * hash ) + getDescriptor().hashCode();
			hash = ( 37 * hash ) + KEY_FIELD_NUMBER;
			hash = ( 53 * hash ) + getKey().hashCode();
			hash = ( 37 * hash ) + VALUE_FIELD_NUMBER;
			hash = ( 53 * hash ) + getValue().hashCode();
			hash = ( 29 * hash ) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom( java.nio.ByteBuffer data )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data );
		}

		public static br.com.proto.ContextProto.ContextRequest
			parseFrom( java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom( com.google.protobuf.ByteString data )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data );
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom( byte[] data )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data );
		}

		public static br.com.proto.ContextProto.ContextRequest
			parseFrom( byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom( java.io.InputStream input )
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input );
		}

		public static br.com.proto.ContextProto.ContextRequest
			parseFrom( java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextRequest parseDelimitedFrom( java.io.InputStream input )
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException( PARSER, input );
		}

		public static br.com.proto.ContextProto.ContextRequest
			parseDelimitedFrom( java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException( PARSER, input, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom( com.google.protobuf.CodedInputStream input )
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input );
		}

		public static br.com.proto.ContextProto.ContextRequest parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry ) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input, extensionRegistry );
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder( br.com.proto.ContextProto.ContextRequest prototype ) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom( prototype );
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom( this );
		}

		@java.lang.Override
		protected Builder newBuilderForType( com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
			Builder builder = new Builder( parent );
			return builder;
		}

		/**
		 * Protobuf type {@code br.com.proto.ContextRequest}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder< Builder > implements
			// @@protoc_insertion_point(builder_implements:br.com.proto.ContextRequest)
			br.com.proto.ContextProto.ContextRequestOrBuilder {

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.com.proto.ContextProto.internal_static_br_com_proto_ContextRequest_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.com.proto.ContextProto.internal_static_br_com_proto_ContextRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						br.com.proto.ContextProto.ContextRequest.class,
						br.com.proto.ContextProto.ContextRequest.Builder.class );
			}

			// Construct using
			// br.com.proto.ContextProto.ContextRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder( com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
				super( parent );
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if ( com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ) {
				}
			}

			public Builder clear() {
				super.clear();
				key_ = "";

				value_ = "";

				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.com.proto.ContextProto.internal_static_br_com_proto_ContextRequest_descriptor;
			}

			public br.com.proto.ContextProto.ContextRequest getDefaultInstanceForType() {
				return br.com.proto.ContextProto.ContextRequest.getDefaultInstance();
			}

			public br.com.proto.ContextProto.ContextRequest build() {
				br.com.proto.ContextProto.ContextRequest result = buildPartial();
				if ( !result.isInitialized() ) {
					throw newUninitializedMessageException( result );
				}
				return result;
			}

			public br.com.proto.ContextProto.ContextRequest buildPartial() {
				br.com.proto.ContextProto.ContextRequest result = new br.com.proto.ContextProto.ContextRequest( this );
				result.key_ = key_;
				result.value_ = value_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField( com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value ) {
				return (Builder) super.setField( field, value );
			}

			public Builder clearField( com.google.protobuf.Descriptors.FieldDescriptor field ) {
				return (Builder) super.clearField( field );
			}

			public Builder clearOneof( com.google.protobuf.Descriptors.OneofDescriptor oneof ) {
				return (Builder) super.clearOneof( oneof );
			}

			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index,
				java.lang.Object value ) {
				return (Builder) super.setRepeatedField( field, index, value );
			}

			public Builder
				addRepeatedField( com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value ) {
				return (Builder) super.addRepeatedField( field, value );
			}

			public Builder mergeFrom( com.google.protobuf.Message other ) {
				if ( other instanceof br.com.proto.ContextProto.ContextRequest ) {
					return mergeFrom( (br.com.proto.ContextProto.ContextRequest) other );
				} else {
					super.mergeFrom( other );
					return this;
				}
			}

			public Builder mergeFrom( br.com.proto.ContextProto.ContextRequest other ) {
				if ( other == br.com.proto.ContextProto.ContextRequest.getDefaultInstance() )
					return this;
				if ( !other.getKey().isEmpty() ) {
					key_ = other.key_;
					onChanged();
				}
				if ( !other.getValue().isEmpty() ) {
					value_ = other.value_;
					onChanged();
				}
				this.mergeUnknownFields( other.unknownFields );
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry ) throws java.io.IOException {
				br.com.proto.ContextProto.ContextRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom( input, extensionRegistry );
				} catch ( com.google.protobuf.InvalidProtocolBufferException e ) {
					parsedMessage = (br.com.proto.ContextProto.ContextRequest) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if ( parsedMessage != null ) {
						mergeFrom( parsedMessage );
					}
				}
				return this;
			}

			private java.lang.Object key_ = "";

			/**
			 * <code>string key = 1;</code>
			 */
			public java.lang.String getKey() {
				java.lang.Object ref = key_;
				if ( !( ref instanceof java.lang.String ) ) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					key_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string key = 1;</code>
			 */
			public com.google.protobuf.ByteString getKeyBytes() {
				java.lang.Object ref = key_;
				if ( ref instanceof String ) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8( (java.lang.String) ref );
					key_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string key = 1;</code>
			 */
			public Builder setKey( java.lang.String value ) {
				if ( value == null ) {
					throw new NullPointerException();
				}

				key_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string key = 1;</code>
			 */
			public Builder clearKey() {

				key_ = getDefaultInstance().getKey();
				onChanged();
				return this;
			}

			/**
			 * <code>string key = 1;</code>
			 */
			public Builder setKeyBytes( com.google.protobuf.ByteString value ) {
				if ( value == null ) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8( value );

				key_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object value_ = "";

			/**
			 * <code>string value = 2;</code>
			 */
			public java.lang.String getValue() {
				java.lang.Object ref = value_;
				if ( !( ref instanceof java.lang.String ) ) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					value_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string value = 2;</code>
			 */
			public com.google.protobuf.ByteString getValueBytes() {
				java.lang.Object ref = value_;
				if ( ref instanceof String ) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8( (java.lang.String) ref );
					value_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string value = 2;</code>
			 */
			public Builder setValue( java.lang.String value ) {
				if ( value == null ) {
					throw new NullPointerException();
				}

				value_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string value = 2;</code>
			 */
			public Builder clearValue() {

				value_ = getDefaultInstance().getValue();
				onChanged();
				return this;
			}

			/**
			 * <code>string value = 2;</code>
			 */
			public Builder setValueBytes( com.google.protobuf.ByteString value ) {
				if ( value == null ) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8( value );

				value_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields( final com.google.protobuf.UnknownFieldSet unknownFields ) {
				return super.setUnknownFieldsProto3( unknownFields );
			}

			public final Builder mergeUnknownFields( final com.google.protobuf.UnknownFieldSet unknownFields ) {
				return super.mergeUnknownFields( unknownFields );
			}

			// @@protoc_insertion_point(builder_scope:br.com.proto.ContextRequest)
		}

		// @@protoc_insertion_point(class_scope:br.com.proto.ContextRequest)
		private static final br.com.proto.ContextProto.ContextRequest DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new br.com.proto.ContextProto.ContextRequest();
		}

		public static br.com.proto.ContextProto.ContextRequest getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser< ContextRequest > PARSER = new com.google.protobuf.AbstractParser< ContextRequest >() {

			public ContextRequest parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new ContextRequest( input, extensionRegistry );
			}
		};

		public static com.google.protobuf.Parser< ContextRequest > parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser< ContextRequest > getParserForType() {
			return PARSER;
		}

		public br.com.proto.ContextProto.ContextRequest getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface ContextResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:br.com.proto.ContextResponse)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string message = 1;</code>
		 */
		java.lang.String getMessage();

		/**
		 * <code>string message = 1;</code>
		 */
		com.google.protobuf.ByteString getMessageBytes();
	}

	/**
	 * Protobuf type {@code br.com.proto.ContextResponse}
	 */
	public static final class ContextResponse extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:br.com.proto.ContextResponse)
		ContextResponseOrBuilder {

		private static final long serialVersionUID = 0L;

		// Use ContextResponse.newBuilder() to construct.
		private ContextResponse( com.google.protobuf.GeneratedMessageV3.Builder< ? > builder ) {
			super( builder );
		}

		private ContextResponse() {
			message_ = "";
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private ContextResponse(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
				.newBuilder();
			try {
				boolean done = false;
				while ( !done ) {
					int tag = input.readTag();
					switch ( tag ) {
						case 0:
							done = true;
							break;
						default: {
							if ( !parseUnknownFieldProto3( input, unknownFields, extensionRegistry, tag ) ) {
								done = true;
							}
							break;
						}
						case 10: {
							java.lang.String s = input.readStringRequireUtf8();

							message_ = s;
							break;
						}
					}
				}
			} catch ( com.google.protobuf.InvalidProtocolBufferException e ) {
				throw e.setUnfinishedMessage( this );
			} catch ( java.io.IOException e ) {
				throw new com.google.protobuf.InvalidProtocolBufferException( e ).setUnfinishedMessage( this );
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return br.com.proto.ContextProto.internal_static_br_com_proto_ContextResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return br.com.proto.ContextProto.internal_static_br_com_proto_ContextResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					br.com.proto.ContextProto.ContextResponse.class,
					br.com.proto.ContextProto.ContextResponse.Builder.class );
		}

		public static final int MESSAGE_FIELD_NUMBER = 1;

		private volatile java.lang.Object message_;

		/**
		 * <code>string message = 1;</code>
		 */
		public java.lang.String getMessage() {
			java.lang.Object ref = message_;
			if ( ref instanceof java.lang.String ) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				message_ = s;
				return s;
			}
		}

		/**
		 * <code>string message = 1;</code>
		 */
		public com.google.protobuf.ByteString getMessageBytes() {
			java.lang.Object ref = message_;
			if ( ref instanceof java.lang.String ) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
					.copyFromUtf8( (java.lang.String) ref );
				message_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if ( isInitialized == 1 )
				return true;
			if ( isInitialized == 0 )
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo( com.google.protobuf.CodedOutputStream output ) throws java.io.IOException {
			if ( !getMessageBytes().isEmpty() ) {
				com.google.protobuf.GeneratedMessageV3.writeString( output, 1, message_ );
			}
			unknownFields.writeTo( output );
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if ( size != -1 )
				return size;

			size = 0;
			if ( !getMessageBytes().isEmpty() ) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize( 1, message_ );
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals( final java.lang.Object obj ) {
			if ( obj == this ) {
				return true;
			}
			if ( !( obj instanceof br.com.proto.ContextProto.ContextResponse ) ) {
				return super.equals( obj );
			}
			br.com.proto.ContextProto.ContextResponse other = (br.com.proto.ContextProto.ContextResponse) obj;

			boolean result = true;
			result = result && getMessage().equals( other.getMessage() );
			result = result && unknownFields.equals( other.unknownFields );
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if ( memoizedHashCode != 0 ) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = ( 19 * hash ) + getDescriptor().hashCode();
			hash = ( 37 * hash ) + MESSAGE_FIELD_NUMBER;
			hash = ( 53 * hash ) + getMessage().hashCode();
			hash = ( 29 * hash ) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom( java.nio.ByteBuffer data )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data );
		}

		public static br.com.proto.ContextProto.ContextResponse
			parseFrom( java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom( com.google.protobuf.ByteString data )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data );
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom( byte[] data )
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data );
		}

		public static br.com.proto.ContextProto.ContextResponse
			parseFrom( byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom( data, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom( java.io.InputStream input )
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input );
		}

		public static br.com.proto.ContextProto.ContextResponse
			parseFrom( java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextResponse parseDelimitedFrom( java.io.InputStream input )
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException( PARSER, input );
		}

		public static br.com.proto.ContextProto.ContextResponse
			parseDelimitedFrom( java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException( PARSER, input, extensionRegistry );
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom( com.google.protobuf.CodedInputStream input )
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input );
		}

		public static br.com.proto.ContextProto.ContextResponse parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry ) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException( PARSER, input, extensionRegistry );
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder( br.com.proto.ContextProto.ContextResponse prototype ) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom( prototype );
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom( this );
		}

		@java.lang.Override
		protected Builder newBuilderForType( com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
			Builder builder = new Builder( parent );
			return builder;
		}

		/**
		 * Protobuf type {@code br.com.proto.ContextResponse}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder< Builder > implements
			// @@protoc_insertion_point(builder_implements:br.com.proto.ContextResponse)
			br.com.proto.ContextProto.ContextResponseOrBuilder {

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return br.com.proto.ContextProto.internal_static_br_com_proto_ContextResponse_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return br.com.proto.ContextProto.internal_static_br_com_proto_ContextResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						br.com.proto.ContextProto.ContextResponse.class,
						br.com.proto.ContextProto.ContextResponse.Builder.class );
			}

			// Construct using
			// br.com.proto.ContextProto.ContextResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder( com.google.protobuf.GeneratedMessageV3.BuilderParent parent ) {
				super( parent );
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if ( com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ) {
				}
			}

			public Builder clear() {
				super.clear();
				message_ = "";

				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return br.com.proto.ContextProto.internal_static_br_com_proto_ContextResponse_descriptor;
			}

			public br.com.proto.ContextProto.ContextResponse getDefaultInstanceForType() {
				return br.com.proto.ContextProto.ContextResponse.getDefaultInstance();
			}

			public br.com.proto.ContextProto.ContextResponse build() {
				br.com.proto.ContextProto.ContextResponse result = buildPartial();
				if ( !result.isInitialized() ) {
					throw newUninitializedMessageException( result );
				}
				return result;
			}

			public br.com.proto.ContextProto.ContextResponse buildPartial() {
				br.com.proto.ContextProto.ContextResponse result = new br.com.proto.ContextProto.ContextResponse(
					this );
				result.message_ = message_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField( com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value ) {
				return (Builder) super.setField( field, value );
			}

			public Builder clearField( com.google.protobuf.Descriptors.FieldDescriptor field ) {
				return (Builder) super.clearField( field );
			}

			public Builder clearOneof( com.google.protobuf.Descriptors.OneofDescriptor oneof ) {
				return (Builder) super.clearOneof( oneof );
			}

			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index,
				java.lang.Object value ) {
				return (Builder) super.setRepeatedField( field, index, value );
			}

			public Builder
				addRepeatedField( com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value ) {
				return (Builder) super.addRepeatedField( field, value );
			}

			public Builder mergeFrom( com.google.protobuf.Message other ) {
				if ( other instanceof br.com.proto.ContextProto.ContextResponse ) {
					return mergeFrom( (br.com.proto.ContextProto.ContextResponse) other );
				} else {
					super.mergeFrom( other );
					return this;
				}
			}

			public Builder mergeFrom( br.com.proto.ContextProto.ContextResponse other ) {
				if ( other == br.com.proto.ContextProto.ContextResponse.getDefaultInstance() )
					return this;
				if ( !other.getMessage().isEmpty() ) {
					message_ = other.message_;
					onChanged();
				}
				this.mergeUnknownFields( other.unknownFields );
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry ) throws java.io.IOException {
				br.com.proto.ContextProto.ContextResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom( input, extensionRegistry );
				} catch ( com.google.protobuf.InvalidProtocolBufferException e ) {
					parsedMessage = (br.com.proto.ContextProto.ContextResponse) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if ( parsedMessage != null ) {
						mergeFrom( parsedMessage );
					}
				}
				return this;
			}

			private java.lang.Object message_ = "";

			/**
			 * <code>string message = 1;</code>
			 */
			public java.lang.String getMessage() {
				java.lang.Object ref = message_;
				if ( !( ref instanceof java.lang.String ) ) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					message_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string message = 1;</code>
			 */
			public com.google.protobuf.ByteString getMessageBytes() {
				java.lang.Object ref = message_;
				if ( ref instanceof String ) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8( (java.lang.String) ref );
					message_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string message = 1;</code>
			 */
			public Builder setMessage( java.lang.String value ) {
				if ( value == null ) {
					throw new NullPointerException();
				}

				message_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string message = 1;</code>
			 */
			public Builder clearMessage() {

				message_ = getDefaultInstance().getMessage();
				onChanged();
				return this;
			}

			/**
			 * <code>string message = 1;</code>
			 */
			public Builder setMessageBytes( com.google.protobuf.ByteString value ) {
				if ( value == null ) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8( value );

				message_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields( final com.google.protobuf.UnknownFieldSet unknownFields ) {
				return super.setUnknownFieldsProto3( unknownFields );
			}

			public final Builder mergeUnknownFields( final com.google.protobuf.UnknownFieldSet unknownFields ) {
				return super.mergeUnknownFields( unknownFields );
			}

			// @@protoc_insertion_point(builder_scope:br.com.proto.ContextResponse)
		}

		// @@protoc_insertion_point(class_scope:br.com.proto.ContextResponse)
		private static final br.com.proto.ContextProto.ContextResponse DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new br.com.proto.ContextProto.ContextResponse();
		}

		public static br.com.proto.ContextProto.ContextResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser< ContextResponse > PARSER = new com.google.protobuf.AbstractParser< ContextResponse >() {

			public ContextResponse parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry )
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new ContextResponse( input, extensionRegistry );
			}
		};

		public static com.google.protobuf.Parser< ContextResponse > parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser< ContextResponse > getParserForType() {
			return PARSER;
		}

		public br.com.proto.ContextProto.ContextResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_br_com_proto_ContextRequest_descriptor;

	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_br_com_proto_ContextRequest_fieldAccessorTable;

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_br_com_proto_ContextResponse_descriptor;

	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_br_com_proto_ContextResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\022ContextProto.proto\022\014br.com.proto\",\n\016Co"
			+ "ntextRequest\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t"
			+ "\"\"\n\017ContextResponse\022\017\n\007message\030\001 \001(\t2\252\002\n"
			+ "\016ContextService\022E\n\006insert\022\034.br.com.proto"
			+ ".ContextRequest\032\035.br.com.proto.ContextRe" + "sponse\022E\n\006update\022\034.br.com.proto.ContextR"
			+ "equest\032\035.br.com.proto.ContextResponse\022E\n"
			+ "\006delete\022\034.br.com.proto.ContextRequest\032\035."
			+ "br.com.proto.ContextResponse\022C\n\004find\022\034.b"
			+ "r.com.proto.ContextRequest\032\035.br.com.prot", "o.ContextResponseb\006proto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {

			public com.google.protobuf.ExtensionRegistry
				assignDescriptors( com.google.protobuf.Descriptors.FileDescriptor root ) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
			descriptorData,
			new com.google.protobuf.Descriptors.FileDescriptor[] {},
			assigner );
		internal_static_br_com_proto_ContextRequest_descriptor = getDescriptor().getMessageTypes().get( 0 );
		internal_static_br_com_proto_ContextRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_br_com_proto_ContextRequest_descriptor, new java.lang.String[] { "Key", "Value", } );
		internal_static_br_com_proto_ContextResponse_descriptor = getDescriptor().getMessageTypes().get( 1 );
		internal_static_br_com_proto_ContextResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_br_com_proto_ContextResponse_descriptor, new java.lang.String[] { "Message", } );
	}

	// @@protoc_insertion_point(outer_class_scope)
}
